version: '2'
services:
  web:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.local
    tty: true
    stdin_open: true
    privileged: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.local'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    volumes:
      - shared_etc:/etc/gitlab
      - shared_opt:/var/opt/gitlab
      - shared_log:/var/log/gitlab
volumes:
  shared_etc:
    driver: rancher-nfs
    driver_opts:
      exportBase: /gitlabdata/etc/gitlab
  shared_opt:
    driver: rancher-nfs
    driver_opts:
      exportBase: /gitlabdata/var/opt/gitlab
  shared_log:
    driver: rancher-nfs
    driver_opts:
      exportBase: /gitlabdata/var/log/gitlab
