version: '2'
services:
  web:
    image: mediawiki:latest
    tty: true
    stdin_open: true
    links:
      - db
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    volumes:
      - shared_images:/var/www/html/images
      - shared_settings:/var/www/html/LocalSettings.php
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - shared_data:/var/www/html/data
volumes:
  shared_data:
    driver: rancher-nfs
    driver_opts:
      exportBase: /mediawikidata/var/www/html/data
  shared_images:
    driver: rancher-nfs
    driver_opts:
      exportBase: /mediawikidata/var/www/html/images
  shared_settings:
    driver: rancher-nfs
    driver_opts:
      exportBase: /mediawikidata/var/www/html/LocalSettings.php
