version: '2'
services:
  web:
    image: alexandersaenen/mediawiki:latest
    tty: true
    stdin_open: true
    links:
      - db
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    volumes:
      - shared_images:/var/www/html/images
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - shared_data:/var/www/html/data
volumes:
  shared_data:
    driver: rancher-nfs
    driver_opts:
      exportBase: /mediawikidata/var/www/html/data
  shared_images:
    driver: rancher-nfs
    driver_opts:
      exportBase: /mediawikidata/var/www/html/images
