version: '2'
services:
  web:
    image: mediawiki
    tty: true
    stdin_open: true
    links:
      - db
    labels:
      io.rancher.scheduler.global: 'true'
    volumes:
      - type: volume
        source: shared_web
        target: /var/www/html/images
        volume:
          nocopy: false
    # - ./LocalSettings.php:/var/www/html/LocalSettings.php
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - type: volume
        source: shared_web
        target: /var/www/html/data
        volume:
          nocopy: false
volumes:
  shared_web:
    driver: rancher-nfs
    driver_opts:
      exportBase: /mediawikidata
